AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal template with only the S3 bucket to test early validation
Resources:
  UserProfileImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
        - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - '*'
          AllowedMethods:
          - GET
          - PUT
          - POST
          - HEAD
          AllowedOrigins:
          - http://127.0.0.1:8000
          - http://localhost:8000
          - http://localhost
          - https://d369y0ycnp7jn3.amplifyapp.com
          MaxAgeSeconds: 3000
