AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Engineer Movement Report backend using Lambda, API Gateway, DynamoDB,
  and Cognito
Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
Resources:
  ReportsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''GET,POST,PUT,DELETE,OPTIONS'''
        AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
        AllowOrigin: '''*'''
    Metadata:
      SamResourceId: ReportsApi
  ReportsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: engineer-movement-reports
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: pk
        AttributeType: S
      - AttributeName: sk
        AttributeType: S
      KeySchema:
      - AttributeName: pk
        KeyType: HASH
      - AttributeName: sk
        KeyType: RANGE
    Metadata:
      SamResourceId: ReportsTable
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: engineer-movement-report-users
      AutoVerifiedAttributes:
      - email
      UsernameAttributes:
      - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
    Metadata:
      SamResourceId: UserPool
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: engineer-movement-report-client
      UserPoolId:
        Ref: UserPool
      ExplicitAuthFlows:
      - ALLOW_USER_PASSWORD_AUTH
      - ALLOW_REFRESH_TOKEN_AUTH
    Metadata:
      SamResourceId: UserPoolClient
  CreateReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-vaj00qpavrhm/4354b707333b72f2af36d018356fd265
      Handler: index.handler
      Environment:
        Variables:
          REPORTS_TABLE:
            Ref: ReportsTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ReportsTable
      Events:
        CreateReportApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: ReportsApi
            Path: /reports
            Method: post
    Metadata:
      SamResourceId: CreateReportFunction
  UserProfilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: engineer-user-profiles
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      - AttributeName: tenantId
        AttributeType: S
      KeySchema:
      - AttributeName: userId
        KeyType: HASH
      - AttributeName: tenantId
        KeyType: RANGE
    Metadata:
      SamResourceId: UserProfilesTable
  UserProfileImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
        - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - '*'
          AllowedMethods:
          - GET
          - PUT
          - POST
          - HEAD
          AllowedOrigins:
          - http://localhost:8000
          - https://d369y0ycnp7jn3.amplifyapp.com
    Metadata:
      SamResourceId: UserProfileImagesBucket
  ProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-vaj00qpavrhm/99bb7d8d58178b7bae837221743d7af1
      Handler: index.handler
      Environment:
        Variables:
          USER_PROFILES_TABLE:
            Ref: UserProfilesTable
          PROFILE_IMAGES_BUCKET:
            Ref: UserProfileImagesBucket
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserProfilesTable
      - S3CrudPolicy:
          BucketName:
            Ref: UserProfileImagesBucket
      Events:
        ProfileApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: ReportsApi
            Path: /profile
            Method: any
        ProfileImageUploadApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: ReportsApi
            Path: /profile/image-upload
            Method: any
        ProfileImageRemoveApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: ReportsApi
            Path: /profile/image-remove
            Method: any
    Metadata:
      SamResourceId: ProfileFunction
  ListReportsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-vaj00qpavrhm/84c271eba64957108b7b970ab61077e3
      Handler: index.handler
      Environment:
        Variables:
          REPORTS_TABLE:
            Ref: ReportsTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ReportsTable
      Events:
        ListReportsApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: ReportsApi
            Path: /reports
            Method: get
    Metadata:
      SamResourceId: ListReportsFunction
Outputs:
  UserPoolId:
    Value:
      Ref: UserPool
  UserPoolClientId:
    Value:
      Ref: UserPoolClient
  ApiEndpoint:
    Value:
      Fn::Sub: https://${ReportsApi}.execute-api.${AWS::Region}.amazonaws.com/Prod
