AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test template - S3 bucket minimal Cors
Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
Resources:
  ReportsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: OPTIONS,GET,POST
        AllowHeaders: Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token
        AllowOrigin: '*'
  UserProfileImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
        - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
        - AllowedMethods:
          - GET
          - PUT
          - POST
          - HEAD
          AllowedOrigins:
          - http://127.0.0.1:8000
          - http://localhost:8000
