AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test template with just API
Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
Resources:
  ReportsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: OPTIONS,GET,POST
        AllowHeaders: Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token
        AllowOrigin: '*'
