AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Add a DynamoDB table for user profiles

Resources:
  UserProfilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: engineer-user-profiles
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: tenantId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: tenantId
          KeyType: RANGE
      Tags:
        - Key: Project
          Value: engineer-movement-report
